all:
  hosts:
    server1:
      ansible_host: 172.29.12.225  # наш сервер внедрения для тестирования + 1 доп сервер тестовый. 172.29.12.225, 172.29.12.231
    server2:
      ansible_host: 172.29.12.231 # основной тест для прогона
    # ... остальные сервера
    server3:
      ansible_host: 172.29.12.235 # docker , спросить про тачку (использует Артем, потом клонит на 15 тачек)
  vars:
    ansible_user: sysadm
    ansible_ssh_pass: "your_password" 

# 1. Прописать все наши рабочие серверы
# 2. Прописать все доп. серверы для разработчиков + указать команду и пояснение в инструкции


all:
  children:
    test_servers:   # Рабочие сервера всей команды
      hosts:
        server1:
          ansible_host: 172.29.12.225
        server2:
          ansible_host: 172.29.12.231
        server3:
          ansible_host: 172.29.12.229
    hosts_for_developers:  # Рабочие сервера разработчиков
      hosts:
        server4:
          ansible_host: 172.29.12.ХХ1 # Пример сервера разработчика
        server5:
          ansible_host: 172.29.12.XX2
         
# ansible-playbook -i hosts.yml deploy.yml --limit "test_servers" - запуск деплоя на всех рабочих серверах команды

# ansible-playbook -i hosts.yml deploy.yml --limit "hosts_for_developers" - запуск деплоя на всех рабочих серверах разработчиков

# ansible-playbook -i hosts.yml deploy.yml --limit "serverX" - ограничивает установку только на определенном сервере

# ansible-playbook -i hosts.yml deploy.yml --limit "server1,server4,server" - ограничивает установка только на определенном сервере