all:
  hosts:
    server1:
      ansible_host: 172.29.12.225  # наш сервер внедрения для тестирования + 1 доп сервер тестовый. 172.29.12.225, 172.29.12.231, + 235(docker)
    server2:
      ansible_host: 172.29.12.231 # обновить до 78 версии
    # ... остальные сервера
    server3:
      ansible_host: 172.29.12.235 # docker , спросить про тачку (использует Артем, потом клонит на 15 тачек)
  vars:
    ansible_user: sysadm
    ansible_ssh_private_key_file: ~/.ssh.id_rsa # Здесь переделать по паролю